AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ChargerGPT – An AWS-based student assistant chatbot for UAH campus

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        FEATURE_BEDROCK: "false"  # toggle to "true" after you enable Bedrock access
        DEFAULT_STUDENT_ID: "student123"  # used for simulated schedule lookups
        FEATURE_S3_DATA: "false"  # when true, Lambda will read optional JSON data from S3 instead of DynamoDB
        S3_BUILDINGS_KEY: "data/buildings.json"
        S3_SCHEDULES_KEY: "data/schedules.json"
        S3_INSTRUCTORS_KEY: "data/instructors.json"
        FEATURE_CONVO_HISTORY: "true"
        S3_NLU_RULES_KEY: "config/nlu_rules.json"
        CONVERSATIONS_TTL_DAYS: "30"

Parameters:
  ProjectPrefix:
    Type: String
    Default: chargergpt
  Stage:
    Type: String
    Default: dev

Resources:
  FaqsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectPrefix}-${Stage}-faqs-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  BuildingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-${Stage}-buildings"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: building_id
          AttributeType: S
      KeySchema:
        - AttributeName: building_id
          KeyType: HASH
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  SchedulesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-${Stage}-schedules"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: student_id
          AttributeType: S
        - AttributeName: course_code
          AttributeType: S
      KeySchema:
        - AttributeName: student_id
          KeyType: HASH
        - AttributeName: course_code
          KeyType: RANGE
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  InstructorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-${Stage}-instructors"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: course_code
          AttributeType: S
      KeySchema:
        - AttributeName: course_code
          KeyType: HASH
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectPrefix}-${Stage}-conversations"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: memory_key
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: memory_key
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  ChargerGPTFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-handler"
      Handler: charger_gpt/handler.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          TABLE_BUILDINGS: !Ref BuildingsTable
          TABLE_SCHEDULES: !Ref SchedulesTable
          TABLE_INSTRUCTORS: !Ref InstructorsTable
          TABLE_CONVERSATIONS: !Ref ConversationsTable
          S3_BUCKET_FAQS: !Ref FaqsBucket
          BEDROCK_MODEL_ID: ""  # fill when you enable Bedrock
          HOURS_FUNCTION_NAME: !Ref HoursFunction
          LOCATION_FUNCTION_NAME: !Ref LocationFunction
          SCHEDULE_FUNCTION_NAME: !Ref ScheduleFunction
          INSTRUCTOR_FUNCTION_NAME: !Ref InstructorFunction
          FAQ_FUNCTION_NAME: !Ref FAQFunction
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:PutItem
              Resource:
                - !GetAtt BuildingsTable.Arn
                - !GetAtt SchedulesTable.Arn
                - !GetAtt InstructorsTable.Arn
                - !GetAtt ConversationsTable.Arn
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${FaqsBucket}"
                - !Sub "arn:aws:s3:::${FaqsBucket}/*"
            # Bedrock invoke permission (feature-flagged in code)
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
            # Allow router to invoke worker lambdas
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt HoursFunction.Arn
                - !GetAtt LocationFunction.Arn
                - !GetAtt ScheduleFunction.Arn
                - !GetAtt InstructorFunction.Arn
                - !GetAtt FAQFunction.Arn
      Events:
        # Example API event to allow test via API Gateway if needed later
        ApiEvent:
          Type: Api
          Properties:
            Path: /ping
            Method: get

  # Worker functions (smaller, intent-focused lambdas)
  HoursFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-hours"
      Handler: charger_gpt/workers/hours.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          TABLE_BUILDINGS: !Ref BuildingsTable
          S3_BUCKET_FAQS: !Ref FaqsBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !GetAtt BuildingsTable.Arn
                - !Sub "arn:aws:s3:::${FaqsBucket}"
                - !Sub "arn:aws:s3:::${FaqsBucket}/*"

  LocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-location"
      Handler: charger_gpt/workers/location.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          TABLE_BUILDINGS: !Ref BuildingsTable
          S3_BUCKET_FAQS: !Ref FaqsBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !GetAtt BuildingsTable.Arn
                - !Sub "arn:aws:s3:::${FaqsBucket}"
                - !Sub "arn:aws:s3:::${FaqsBucket}/*"

  ScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-schedule"
      Handler: charger_gpt/workers/schedule.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          TABLE_SCHEDULES: !Ref SchedulesTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt SchedulesTable.Arn

  InstructorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-instructor"
      Handler: charger_gpt/workers/instructor.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          TABLE_INSTRUCTORS: !Ref InstructorsTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt InstructorsTable.Arn

  FAQFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectPrefix}-${Stage}-faq"
      Handler: charger_gpt/workers/faq.lambda_handler
      CodeUri: lambdas/
      Environment:
        Variables:
          S3_BUCKET_FAQS: !Ref FaqsBucket
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub "arn:aws:s3:::${FaqsBucket}"
                - !Sub "arn:aws:s3:::${FaqsBucket}/*"

Outputs:
  FunctionName:
    Value: !Ref ChargerGPTFunction
  BuildingsTableName:
    Value: !Ref BuildingsTable
  SchedulesTableName:
    Value: !Ref SchedulesTable
  InstructorsTableName:
    Value: !Ref InstructorsTable
  ConversationsTableName:
    Value: !Ref ConversationsTable
  FaqsBucketName:
    Value: !Ref FaqsBucket
